version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: sms-mysql
    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: Ashmina@2000
      MYSQL_DATABASE: student


    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - sms-network
  student-management-system:
      build: .
      container_name: sms-backend
      restart: always
      depends_on:
        - mysql

      ports:
        - "8080:8080"

      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: Ashmina@2000


      volumes:
        - ./uploads:/app/uploads

      networks:
         - sms-network

volumes:
  mysql-data:

networks:
  sms-network:


